wordHunt: wordHunt.cpp
	g++ -o wordHunt wordHunt.cpp 
test: wordHunt.cpp
	g++ -o wordHunt wordHunt.cpp 
	./wordHunt

test2: wordHunt2.cpp
	g++ -o wordHunt2 wordHunt2.cpp
	./wordHunt2

run1:
	./wordHunt1

run2: 
	./wordHunt2

clean:
	rm -f wordHunt wordHunt2